# Generated by Django 5.2.17 on 2026-09-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_systemsettings_daily_posting_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeapiusage',
            name='quota_used',
            field=models.IntegerField(default=0, help_text='Total estimated quota units consumed today (standard daily limit is 100,000)'),
        ),
    ]
