# Generated by Django 5.2.11 on 2026-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadarChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, help_text='Official YouTube Channel ID (e.g. UCxxxxxxxxxxxxxx)', max_length=100, unique=True)),
                ('channel_name', models.CharField(help_text='YouTube Channel Display Title', max_length=255)),
                ('handle', models.CharField(blank=True, default='', help_text='YouTube Channel Handle (e.g. @channel_name)', max_length=100)),
                ('channel_url', models.URLField(blank=True, default='', help_text='Full YouTube Channel URL', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Channel avatar / thumbnail URL', max_length=1000)),
                ('uploads_playlist_id', models.CharField(blank=True, default='', help_text='Uploads playlist ID (UUxxxxxxxxxxxxxx) for low-quota fetching', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this channel is actively monitored in the radar feed')),
                ('subscriber_count', models.BigIntegerField(default=0, help_text='Approximate subscriber count')),
                ('video_count', models.IntegerField(default=0, help_text='Total video count from YouTube')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp when this channel was last synced', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radar Tracked Channel',
                'verbose_name_plural': 'Radar Tracked Channels',
                'ordering': ['channel_name'],
            },
        ),
    ]
