# Generated by Django 5.2.17 on 2026-09-18 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=20)),
                ('video_title', models.CharField(blank=True, default='', max_length=500)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_radar_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seen Radar Video',
                'verbose_name_plural': 'Seen Radar Videos',
                'ordering': ['-marked_at'],
                'unique_together': {('user', 'video_id')},
            },
        ),
    ]
