# Generated by Django 5.2.11 on 2026-09-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_publishingjob_upload_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, help_text='TikTok unique user identifier (open_id)', max_length=200, unique=True)),
                ('union_id', models.CharField(blank=True, default='', max_length=200)),
                ('display_name', models.CharField(help_text='TikTok display name / username', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=1000)),
                ('follower_count', models.BigIntegerField(default=0)),
                ('following_count', models.BigIntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('bio_description', models.TextField(blank=True, default='')),
                ('profile_url', models.URLField(blank=True, default='', max_length=500)),
                ('access_token', models.TextField(blank=True, default='', help_text='Current OAuth access token')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth refresh token (365-day lifetime)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the current access_token expires', null=True)),
                ('token_scope', models.TextField(blank=True, default='', help_text='Granted OAuth scopes')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TikTok Account',
                'verbose_name_plural': 'TikTok Accounts',
                'ordering': ['-is_default', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='platform',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok')], db_index=True, default='YOUTUBE', help_text='Target publishing platform', max_length=10),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_branded_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_disable_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_disable_duet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_disable_stitch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_privacy_level',
            field=models.CharField(blank=True, choices=[('PUBLIC_TO_EVERYONE', 'Public — Everyone'), ('MUTUAL_FOLLOW_FRIENDS', 'Friends Only'), ('SELF_ONLY', 'Private (Only Me)')], default='PUBLIC_TO_EVERYONE', max_length=30),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_publish_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_share_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_video_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publishingjob',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Video description / caption body'),
        ),
        migrations.AlterField(
            model_name='publishingjob',
            name='title',
            field=models.CharField(help_text='Video title / caption (max 100 chars YouTube, 2200 chars TikTok)', max_length=150),
        ),
        migrations.AlterField(
            model_name='publishingjob',
            name='upload_engine',
            field=models.CharField(choices=[('API_V3', 'YouTube Data API v3 (Official API)'), ('BROWSER_AUTOMATION', 'Browser Automation (Zero Quota)'), ('STUDIO_DISPATCHER', '1-Click Studio Assistant (Clipboard)'), ('TIKTOK_DIRECT', 'TikTok Direct Post API'), ('TIKTOK_INBOX', 'TikTok Inbox Draft')], default='API_V3', help_text='Engine / protocol used to upload video', max_length=30),
        ),
        migrations.AddField(
            model_name='publishingjob',
            name='tiktok_account',
            field=models.ForeignKey(blank=True, help_text='Target TikTok account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='publishing.tiktokaccount'),
        ),
    ]
