# Generated by Django 5.2.11 on 2026-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_automationpipeline_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricvideoproject',
            name='time_offset',
            field=models.FloatField(default=0.0),
        ),
    ]
