# Generated by Django 5.2.17 on 2026-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0021_shortvideoanalysis_and_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortvideoproject',
            name='audio_normalize',
            field=models.BooleanField(default=True, help_text='Apply EBU R128 audio loudness normalization'),
        ),
        migrations.AddField(
            model_name='shortvideoproject',
            name='caption_style',
            field=models.CharField(choices=[('BEAST_YELLOW', 'MrBeast Yellow Highlight'), ('NEON_CYAN', 'Cyber Neon Cyan'), ('FIRE_PUNCH', 'Fire Punch Orange/Red'), ('CLEAN_WHITE', 'Classic Bold White')], default='BEAST_YELLOW', max_length=30),
        ),
        migrations.AddField(
            model_name='shortvideoproject',
            name='visual_progress_bar',
            field=models.BooleanField(default=True, help_text='Render animated bottom retention progress bar'),
        ),
    ]
