# Generated by Django 5.2.17 on 2026-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_shortvideoproject_audio_normalize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortvideoproject',
            name='remove_pauses',
            field=models.BooleanField(default=False, help_text='Auto-remove silences and filler gaps (Step 8: tighten pacing)'),
        ),
    ]
