# Generated by Django 5.2.17 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('studio', '0023_shortvideoproject_remove_pauses')]

    operations = [
        migrations.CreateModel(
            name='NarrationVideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled POV Story', max_length=255)),
                ('script', models.TextField(blank=True, default='')),
                ('voice', models.CharField(default='af_heart', max_length=80)),
                ('aspect_ratio', models.CharField(choices=[('9:16', 'Vertical 9:16'), ('16:9', 'Landscape 16:9')], default='9:16', max_length=8)),
                ('scenes_data', models.JSONField(blank=True, default=list)),
                ('narration_audio', models.FileField(blank=True, null=True, upload_to='studio/narration_audio/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='studio/narration_videos/')),
                ('duration_seconds', models.FloatField(default=0)),
                ('render_status', models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
