# Generated by Django 5.2.11 on 2026-10-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0024_narrationvideoproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrationvideoproject',
            name='caption_font_size',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='narrationvideoproject',
            name='caption_position',
            field=models.CharField(choices=[('BOTTOM', 'Bottom Third'), ('CENTER', 'Center Focal'), ('TOP', 'Top Header')], default='BOTTOM', max_length=20),
        ),
        migrations.AddField(
            model_name='narrationvideoproject',
            name='caption_style',
            field=models.CharField(choices=[('BEAST_YELLOW', 'MrBeast Yellow Highlight'), ('NEON_CYAN', 'Cyber Neon Cyan'), ('FIRE_PUNCH', 'Fire Punch Orange'), ('CLEAN_WHITE', 'Classic Bold White'), ('CINEMATIC', 'Cinematic Minimal Serif'), ('BOXED_DARK', 'Dark Pill Box')], default='BEAST_YELLOW', max_length=30),
        ),
        migrations.AddField(
            model_name='narrationvideoproject',
            name='show_captions',
            field=models.BooleanField(default=True),
        ),
    ]
